

all: uses_comparisons without_comparisons

uses_comparisons: uses_comparisons.c
	g++ uses_comparisons.c -o uses_comparisons

without_comparisons: without_comparisons.c
	g++ without_comparisons.c -o without_comparisons

